version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    command: "python app.py"
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.4.27
    container_name: mariadb-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: flask_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
