# Utiliza una imagen ligera de Nginx como base
FROM nginx:alpine

# Elimina la configuración predeterminada de Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copia los archivos del frontend a la carpeta de Nginx
COPY . /usr/share/nginx/html

# Exponer el puerto 80 para que pueda ser accedido desde fuera del contenedor
EXPOSE 80

# Inicia Nginx cuando se ejecute el contenedor
CMD ["nginx", "-g", "daemon off;"]
